// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Bibliocanto.Model.Models;

public partial class Bibliocanto_DBContext : DbContext
{
    public Bibliocanto_DBContext(DbContextOptions<Bibliocanto_DBContext> options)
        : base(options)
    {
    }

    public Bibliocanto_DBContext()
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)

=> optionsBuilder.UseSqlServer("data source=NOTEBOOK-MARCOS\\SQLEXPRESS;Initial Catalog=Bibliocanto_DB;User Id=sa;Password=2000@edu.sau;TrustserverCertificate=True");
    public virtual DbSet<ComentarioPost> ComentarioPosts { get; set; }

    public virtual DbSet<Genero> Generos { get; set; }

    public virtual DbSet<LivrosUser> LivrosUsers { get; set; }

    public virtual DbSet<PostagemBlog> PostagemBlogs { get; set; }

    public virtual DbSet<SimNao> SimNaos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ComentarioPost>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Comentar__3214EC0716008289");

            entity.ToTable("Comentario_Post");

            entity.Property(e => e.Comentario)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.IdPost).HasColumnName("Id_Post");
            entity.Property(e => e.IdUser)
                .HasMaxLength(450)
                .HasColumnName("Id_user");
        });

        modelBuilder.Entity<Genero>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Generos__3214EC071D39DD40");

            entity.Property(e => e.Descricao)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<LivrosUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Livros_U__3214EC078E30103C");

            entity.ToTable("Livros_User");

            entity.Property(e => e.Autor)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Capa).HasColumnType("image");
            entity.Property(e => e.Comentario)
                .HasMaxLength(5000)
                .IsUnicode(false);
            entity.Property(e => e.IdUser)
                .HasMaxLength(450)
                .HasColumnName("Id_user");
            entity.Property(e => e.Nome)
                .HasMaxLength(150)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PostagemBlog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Postagem__3214EC0786F854C7");

            entity.ToTable("Postagem_Blog");

            entity.Property(e => e.Descricao)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.IdUser)
                .HasMaxLength(450)
                .HasColumnName("id_user");
            entity.Property(e => e.Titulo)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<SimNao>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SimNao__3214EC07E93EFDFF");

            entity.ToTable("SimNao");

            entity.Property(e => e.Descricao)
                .HasMaxLength(3)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}