// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bibliocanto.Model.Models;

public partial class ComentarioPost
{
    public int Id { get; set; }

    public int? IdPost { get; set; }

    public string IdUser { get; set; }

    public string Comentario { get; set; }
}