// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bibliocanto.Model.Models;

public partial class PostagemBlog
{
    public int Id { get; set; }

    public string IdUser { get; set; }

    public string Titulo { get; set; }

    public string Descricao { get; set; }
}